Traceback (most recent call last):
  File "C:\Users\01987984\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\01987984\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\01987984\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\01987984\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\01987984\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\01987984\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\01987984\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\01987984\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import schemdraw
import schemdraw.elements as elm
with schemdraw.Drawing(file='nodal-example-1.svg') as d:
    d.push()
    d += elm.GroundSignal()
    d.pop()
    d += elm.ResistorIEC().up().label(['+', '$V_1$', '-'])
    d += (A := elm.Dot().label('A'))
    d += elm.ResistorIEC().right().label(['+','$V_2$', '-'])
    d += (B := elm.Dot().label('B'))
    d += elm.ResistorIEC().right().label(['-','$V_3$', '+'])
    d += (C := elm.Dot().label('C'))
    d += elm.ResistorIEC().down().label(['+','$V_4$', '-'])
    d += elm.Line().left()
    d.push()
    d += elm.ResistorIEC().up().label(['-','$V_4$', '+'])
    d.pop()
    d += elm.Line().left()
    d.move_from(A, 0, 0)
    d += elm.Line().up()
    d += elm.ResistorIEC().right().label(['+','$V_6$', '-']).length(6)
    d += elm.Line().down()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12076\581861130.py[0m in [0;36m<module>[1;34m[0m
[0;32m     17[0m     [0md[0m[1;33m.[0m[0mpop[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     18[0m     [0md[0m [1;33m+=[0m [0melm[0m[1;33m.[0m[0mLine[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mleft[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 19[1;33m     [0md[0m[1;33m.[0m[0mmove_from[0m[1;33m([0m[0mA[0m[1;33m,[0m [1;36m0[0m[1;33m,[0m [1;36m0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     20[0m     [0md[0m [1;33m+=[0m [0melm[0m[1;33m.[0m[0mLine[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mup[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     21[0m     [0md[0m [1;33m+=[0m [0melm[0m[1;33m.[0m[0mResistorIEC[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mright[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mlabel[0m[1;33m([0m[1;33m[[0m[1;34m'+'[0m[1;33m,[0m[1;34m'$V_6$'[0m[1;33m,[0m [1;34m'-'[0m[1;33m][0m[1;33m)[0m[1;33m.[0m[0mlength[0m[1;33m([0m[1;36m6[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\schemdraw\schemdraw.py[0m in [0;36mmove_from[1;34m(self, ref, dx, dy, theta)[0m
[0;32m    278[0m             [0mtheta[0m [1;32mif[0m [0mprovided[0m[1;33m.[0m[1;33m[0m[1;33m[0m[0m
[0;32m    279[0m         '''
[1;32m--> 280[1;33m         [0mself[0m[1;33m.[0m[0mhere[0m [1;33m=[0m [1;33m([0m[0mref[0m[1;33m.[0m[0mx[0m [1;33m+[0m [0mdx[0m[1;33m,[0m [0mref[0m[1;33m.[0m[0my[0m [1;33m+[0m [0mdy[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    281[0m         [1;32mif[0m [0mtheta[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    282[0m             [0mself[0m[1;33m.[0m[0mtheta[0m [1;33m=[0m [0mtheta[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\schemdraw\elements\elements.py[0m in [0;36m__getattr__[1;34m(self, name)[0m
[0;32m     81[0m         [1;32mif[0m [0mname[0m [1;32min[0m [0mvars[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m.[0m[0mget[0m[1;33m([0m[1;34m'absanchors'[0m[1;33m,[0m [1;33m{[0m[1;33m}[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     82[0m             [1;32mreturn[0m [0mvars[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m.[0m[0mget[0m[1;33m([0m[1;34m'absanchors'[0m[1;33m)[0m[1;33m[[0m[0mname[0m[1;33m][0m  [1;31m# type: ignore[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 83[1;33m         [1;32mraise[0m [0mAttributeError[0m[1;33m([0m[1;34mf'{name} not defined in Element'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     84[0m [1;33m[0m[0m
[0;32m     85[0m     [1;32mdef[0m [0mup[0m[1;33m([0m[0mself[0m[1;33m)[0m [1;33m->[0m [1;34m'Element'[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mAttributeError[0m: x not defined in Element
AttributeError: x not defined in Element

