Traceback (most recent call last):
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kootsoop/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
with schemdraw.Drawing(file='super-example-sub1.svg') as d:
    d += (Vs1 := elm.Battery().up().label('$V_{S1}$\n30V', loc='top').reverse())
    d += (R1 := elm.Resistor().right().label('$R_{1}$\n10Î©', loc='top'))
    d += (R3 := elm.Resistor().right().label('$R_{3}$\n10Î©', loc='top'))
    d += elm.LineDot().down().length(d.unit/4)
    d += elm.LineDot().down().length(d.unit/2)
    d += elm.Line().down().length(d.unit/4)
    d += (LineB := elm.Line().left().tox(Vs1.start))
    d += (GndSig := elm.GroundSignal())
    d += (R2 := elm.Resistor().at(R1.end).down().label('$R_{2}$\n10Î©', loc='top'))
    d += elm.CurrentLabelInline(direction='in', ofst=0.3).at(R2.end).label('$I_O^{(1)}$')
    d += elm.Dot().color('red').at(R2.start).label('$V_A^{(1)}$')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/65/qy_bbqpj2x3470cgr0fmhyc40000gn/T/ipykernel_31391/644060377.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m     [0md[0m [0;34m+=[0m [0;34m([0m[0mR1[0m [0;34m:=[0m [0melm[0m[0;34m.[0m[0mResistor[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mright[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mlabel[0m[0;34m([0m[0;34m'$R_{1}$\n10Î©'[0m[0;34m,[0m [0mloc[0m[0;34m=[0m[0;34m'top'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0md[0m [0;34m+=[0m [0;34m([0m[0mR3[0m [0;34m:=[0m [0melm[0m[0;34m.[0m[0mResistor[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mright[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mlabel[0m[0;34m([0m[0;34m'$R_{3}$\n10Î©'[0m[0;34m,[0m [0mloc[0m[0;34m=[0m[0;34m'top'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m     [0md[0m [0;34m+=[0m [0melm[0m[0;34m.[0m[0mLineDot[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mdown[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mlength[0m[0;34m([0m[0md[0m[0;34m.[0m[0munit[0m[0;34m/[0m[0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m     [0md[0m [0;34m+=[0m [0melm[0m[0;34m.[0m[0mLineDot[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mdown[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mlength[0m[0;34m([0m[0md[0m[0;34m.[0m[0munit[0m[0;34m/[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0md[0m [0;34m+=[0m [0melm[0m[0;34m.[0m[0mLine[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mdown[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mlength[0m[0;34m([0m[0md[0m[0;34m.[0m[0munit[0m[0;34m/[0m[0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'schemdraw.elements' has no attribute 'LineDot'
AttributeError: module 'schemdraw.elements' has no attribute 'LineDot'

